
# tasks file for adduser and make provide root acces
# Considering that the ansible login has root access
# Change the username and group name according to your requirement
# Usage: ansible-playbook ---.yml --ask-become-pass
---  
  - name : "Create Groups"
    group:
      name: "{{item}}"
      state: "present"
    with_items:
      - wheel
      - group2

  - name : "Create a user"
    user:
        name: "{{item.name}}" 
        create_home: yes 
        group: "{{item.group}}" 
        state: present 
        ssh_key_file: .ssh/id_rsa 
        ssh_key_type: rsa 
    with_items: 
      - { name: 'user11', group: 'wheel' }
      - { name: 'user22', group: 'wheel' }
      - { name: 'user33', group: 'group1' } 

  - name: "Copy the authorized key file from"
    authorized_key:
      user: "{{item.name}}"
      state: "{{item.userstate}}"
      key: "{{ lookup('file', '{{ item.key }}')}}"
    with_items:
      - { name: 'user11', key: 'user11.pub', userstate: 'present' }
      - { name: 'user22', key: 'user22.pub', userstate: 'present' } 
      - { name: 'user33', key: 'user33.pub', userstate: 'present' }

  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: sudo without password for wheel group
    copy:
      content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
      dest: /etc/sudoers.d/wheel_nopasswd
      mode: 0440

  - name: Add sudoers users to wheel group
    user:
      name=user11
      groups=wheel
      append=yes
      state=present
      createhome=yes
